### PR TITLE
Update DefaultErrorStrategy.cpp

### PR DESCRIPTION
**Pull request by nuuman**
Property escape vocabulary reporting

### CODE REVIEW

**Comment by mike-lischke** [comment]
@nuuman, in order to accept your patch I have to ask you to sign the contributors list (add yourself to contributors.txt) and send this to me as well.

**Comment by nuuman** [comment]
Please revert this merge as I do not accept the contributor agreement (as explained in  https://github.com/DanMcLaughlin/antlr4/issues/12)

**Comment by mike-lischke** [comment]
Done

**Comment by nuuman** [comment]
Thanks!

**Pull request merged**
