### PR TITLE
cpp runtime: updated the vs2013 project reflecting the last changes

### PR DESCRIPTION
**Pull request by FloorGoddijn**
Updated the vs2013 project for the cpp runtime in order for it to build without errors again

### CODE REVIEW

**Comment by mike-lischke** [comment]
Thanks for the patch.

**Comment by mike-lischke** [comment]
I forgot to ask you to add yourself to the contributors file in the root of the source folder. Otherwise I cannot accept your patch, as trivial as it might be.

**Comment by FloorGoddijn** [comment]
Hi Mike, I was under the impression that I did that ( if I look at the current contributors.txt I see myself add the 104th line).

Regards,
Floor

**Comment by mike-lischke** [comment]
No worries Floor. I realized this and removed my comment already.

**Pull request merged**
